name: ci
on:
  push:
    branches:
      - base
      - main       
 
permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache

      - name: build docs
        run: |
          pip install mkdocs-material
          mkdocs gh-deploy --force
 
      - name: install pre-reqs and build
        run: sudo ./install/installUbuntu.sh
      - name: test
        run: |
          mkdir build
          cd build
          wget https://github.com/oneapi-src/oneTBB/archive/2019_U9.tar.gz
          tar -xvzf 2019_U9.tar.gz
          cmake  -DTBB_DIR=${PWD}/oneTBB-2019_U9  -DCMAKE_PREFIX_PATH=${PWD}/oneTBB-2019_U9/cmake ..
          make -j2
          ./panmat-utils --help